version: '{build}'

image: Visual Studio 2017

branches:
    only:
        - master

pull_requests:
    do_not_increment_build_number: true

environment:
    BUILD: $(APPVEYOR_BUILD_NUMBER)

build_script:
    - ps: ./build.ps1

nuget:
    disable_publish_on_pr: true

test: off

artifacts:
    - path: .\artifacts\*\*
