version: '{build}'

image: Visual Studio 2017

pull_requests:
    do_not_increment_build_number: true

environment:
    BUILD: $(APPVEYOR_BUILD_NUMBER)

build_script:
    - ps: ./build.ps1

nuget:
    disable_publish_on_pr: true

test: off

artifacts:
    - path: .\artifacts\*\*

deploy:
    - provider: NuGet
      api_key:
          secure: pMA56H6cIXL1IGvlssfKFdAN+gGHmGrSGcGLmEXje5gGBuaiEC28PT4NFu/XMvBu
      skip_symbols: true
      on:
          appveyor_repo_tag: true
