version: '{build}'

image: Visual Studio 2017

branches:
    only:
        - /^(master|[1-9][0-9]*\.[1-9][0-9]*\.[1-9][0-9]*(-.+)?)$/

pull_requests:
    do_not_increment_build_number: true

environment:
    BUILD: $(APPVEYOR_BUILD_NUMBER)

build_script:
    - ps: ./build.ps1

nuget:
    disable_publish_on_pr: true

test: off

artifacts:
    - path: .\artifacts\*\*

deploy:
    - provider: NuGet
      api_key:
          secure: Dgj/78UqI7Sn62XajiI6SQp0JoT6YTK+k/GuoJ335F4rLnpKFGPf7SLdnHuDaaip
      skip_symbols: true
      on:
          appveyor_repo_tag: true
